### ISSUE TITLE
运行airdrop.js报catch异常

### ISSUE THREAD

**Issue by Edison-zhu** [fan31415/TokenAirdrop#1]
(node:12891) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12891) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by fan31415** [comment]
这个Warning不影响代码运行，你可以用低版本的Node.js， 或者我可以更新一下代码。在新版本的Node.js中promise必须主动catch可能的rejection情况。

**Comment by Edison-zhu** [comment]
在报警告之前还有这些错，不知道是不是我的合约出了问题
0xa0e7447E308cA11413A8a51E05c4C81d7905cC28
(node:12891) UnhandledPromiseRejectionWarning: Error: invalid address (arg="_to", coderType="address", value="0x6e5C2Daf1ff5eA285F8359Fe61cA1DDFa821EeA1\n0x77ddb7512cC241721C496A582140BCC6B378c5FE\n0xC160C39E3c6De4B4E4193cAF7e0769a3E6002482\n0x74c010E2A471fAA3311053347Ae35D4F121A04eA\n0x5A9C83239C924FF0cFf9A6d85D5b88172D48018A\n0x6D79B956F16711858cD5Eb8E7150523d1F332443\n0xfCa9d0E777fF852Eb0c42Bd59670f73a057431ac\n0xc0940679f59c6ca51B488b4E5F31d276DBe58443\n0xa3ea99e34fcE9AFD77d17c0C83336659b103751F\n0x1747148384dcb001C7f39bAbd1515275A7420e5A\n0xB3BDa3F87991729CCF0ac2da9a1E691F83B7Ad56\n0x22C912A0B04aac1a681aFD5009Eab548420221fb\n0xcfba4851F26553Ee36b3B1843f9eD73879140748\n0x532269b79711D70efeb884143f6D1bDDeD27E61f\n0xC57C781d56AF0322

**Comment by Edison-zhu** [comment]
整体错误是这样
`appledeMacBook-Air:TokenAirdrop1 apple$ node airdrop.js
Holder address: 0xd7153DAb34a41004e3A0fDF8353864BD52Fa2628
Holder key: 101172700a26773e3e60b9bbe3c17ab8b880deb1d8d092171579a1bf204b7aba
token contract address: 0xbb729fa7713d145f129f75318a1a29971fe396bb
1
Block Number:3424753
1000000000000000000000000
49
0
0x6e5C2Daf1ff5eA285F8359Fe61cA1DDFa821EeA1
0x77ddb7512cC241721C496A582140BCC6B378c5FE
0xC160C39E3c6De4B4E4193cAF7e0769a3E6002482
0x74c010E2A471fAA3311053347Ae35D4F121A04eA
0x5A9C83239C924FF0cFf9A6d85D5b88172D48018A
0x6D79B956F16711858cD5Eb8E7150523d1F332443
0xfCa9d0E777fF852Eb0c42Bd59670f73a057431ac
0xc0940679f59c6ca51B488b4E5F31d276DBe58443
0xa3ea99e34fcE9AFD77d17c0C83336659b103751F
0x1747148384dcb001C7f39bAbd1515275A7420e5A
0xB3BDa3F87991729CCF0ac2da9a1E691F83B7Ad56
0x22C912A0B04aac1a681aFD5009Eab548420221fb
0xcfba4851F26553Ee36b3B1843f9eD73879140748
0x532269b79711D70efeb884143f6D1bDDeD27E61f
0xC57C781d56AF0322258D4a692A8E8Af7d6498B2F
0xeEb3240c7c7cAC17a5355Ca987AE7189A26Dda39
0xCe4BCf7608519c7c25056626c8D9DadE9A87d790
0x4f60F62fF4704ec77962B5Bad35aF736B9D73045
0xaD043A0D0b66F323a88C7a4eE32691c7F756234f
0xa100200D3D096d2e7fb5C78D8cddccC50316a17c
0xDCcB425eD0318cB63906A9966c996117c195F723
0x20A4eCA319029891aD483B9429Bd18E9DCF40374
0x3cFDF083a8dE7D94867aD24a77Eb3Da3A49A1509
0xf6879CEb728e2478a408cC8a3B9769707236Ca46
0xa0e7447E308cA11413A8a51E05c4C81d7905cC28
(node:12915) UnhandledPromiseRejectionWarning: Error: invalid address (arg="_to", coderType="address", value="0x6e5C2Daf1ff5eA285F8359Fe61cA1DDFa821EeA1\n0x77ddb7512cC241721C496A582140BCC6B378c5FE\n0xC160C39E3c6De4B4E4193cAF7e0769a3E6002482\n0x74c010E2A471fAA3311053347Ae35D4F121A04eA\n0x5A9C83239C924FF0cFf9A6d85D5b88172D48018A\n0x6D79B956F16711858cD5Eb8E7150523d1F332443\n0xfCa9d0E777fF852Eb0c42Bd59670f73a057431ac\n0xc0940679f59c6ca51B488b4E5F31d276DBe58443\n0xa3ea99e34fcE9AFD77d17c0C83336659b103751F\n0x1747148384dcb001C7f39bAbd1515275A7420e5A\n0xB3BDa3F87991729CCF0ac2da9a1E691F83B7Ad56\n0x22C912A0B04aac1a681aFD5009Eab548420221fb\n0xcfba4851F26553Ee36b3B1843f9eD73879140748\n0x532269b79711D70efeb884143f6D1bDDeD27E61f\n0xC57C781d56AF0322258D4a692A8E8Af7d6498B2F\n0xeEb3240c7c7cAC17a5355Ca987AE7189A26Dda39\n0xCe4BCf7608519c7c25056626c8D9DadE9A87d790\n0x4f60F62fF4704ec77962B5Bad35aF736B9D73045\n0xaD043A0D0b66F323a88C7a4eE32691c7F756234f\n0xa100200D3D096d2e7fb5C78D8cddccC50316a17c\n0xDCcB425eD0318cB63906A9966c996117c195F723\n0x20A4eCA319029891aD483B9429Bd18E9DCF40374\n0x3cFDF083a8dE7D94867aD24a77Eb3Da3A49A1509\n0xf6879CEb728e2478a408cC8a3B9769707236Ca46\n0xa0e7447E308cA11413A8a51E05c4C81d7905cC28")
    at Object.throwError (/Volumes/新加卷/demo/kongtou/TokenAirdrop1/node_modules/ethers/utils/errors.js:68:17)
    at CoderAddress.encode (/Volumes/新加卷/demo/kongtou/TokenAirdrop1/node_modules/ethers/utils/abi-coder.js:467:20)
    at /Volumes/新加卷/demo/kongtou/TokenAirdrop1/node_modules/ethers/utils/abi-coder.js:605:59
    at Array.forEach (<anonymous>)
    at pack (/Volumes/新加卷/demo/kongtou/TokenAirdrop1/node_modules/ethers/utils/abi-coder.js:604:12)
    at CoderTuple.encode (/Volumes/新加卷/demo/kongtou/TokenAirdrop1/node_modules/ethers/utils/abi-coder.js:764:16)
    at AbiCoder.encode (/Volumes/新加卷/demo/kongtou/TokenAirdrop1/node_modules/ethers/utils/abi-coder.js:897:77)
    at ABICoder.encodeParameters (/Volumes/新加卷/demo/kongtou/TokenAirdrop1/node_modules/web3-eth-abi/src/index.js:96:27)
    at /Volumes/新加卷/demo/kongtou/TokenAirdrop1/node_modules/web3-eth-contract/src/index.js:426:24
    at Array.map (<anonymous>)
    at Object._encodeMethodABI (/Volumes/新加卷/demo/kongtou/TokenAirdrop1/node_modules/web3-eth-contract/src/index.js:425:12)
    at Object._processExecuteArguments (/Volumes/新加卷/demo/kongtou/TokenAirdrop1/node_modules/web3-eth-contract/src/index.741:39)
    at Object._executeMethod (/Volumes/新加卷/demo/kongtou/TokenAirdrop1/node_modules/web3-eth-contract/src/index.js:766:54)
    at transferToken (/Volumes/新加卷/demo/kongtou/TokenAirdrop1/airdrop.js:113:67)
    at Timeout.setTimeout [as _onTimeout] (/Volumes/新加卷/demo/kongtou/TokenAirdrop1/airdrop.js:104:19)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
(node:12915) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:12915) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by fan31415** [comment]
我在README中只是给了一个example，你需要用自己的账户地址和密钥替换我的部分，以及修改为自己要投送的地址即可

**Comment by fan31415** [comment]
我没有直接给真实的地址和密钥，所以不能直接运行。你替换为正确的之后应该就没有问题

**Comment by fan31415** [comment]
除此之外，你的private key需要加上0x的前缀，不然可能出现error

**Comment by fan31415** [comment]
我更新了一下代码，mac下文件和windows文件不一致，在文本处理时会不兼容，你可以pull一下再试试

**Comment by Edison-zhu** [comment]
> 我更新了一下代码，mac下文件和windows文件不一致，在文本处理时会不兼容，你可以pull一下再试试
好的，谢谢您
